version: '3'
services:
    app:
        build:
            context: .
        container_name: blog
        ports:
            - 8000:8000
        volumes:
            - .:/app
        command: sh -c "python manage.py makemigrations blog && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
