# Generated by Django 4.2.4 on 2023-08-29 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='keyword_set',
            field=models.ManyToManyField(blank=True, to='blog.keyword'),
        ),
    ]
